version: "3.7"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - 4000:4000
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/app
    depends_on:
      - db
